// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoutePage.Model;

namespace RoutePage.Model.Migrations
{
    [DbContext(typeof(RouteContext))]
    partial class RouteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("RoutePage.Model.Coordinate", b =>
                {
                    b.Property<int>("CoordinateId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Latitude");

                    b.Property<float>("Longitude");

                    b.Property<string>("RouteId");

                    b.HasKey("CoordinateId");

                    b.HasIndex("RouteId");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("RoutePage.Model.Route", b =>
                {
                    b.Property<string>("RouteId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("RouteId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("RoutePage.Model.Coordinate", b =>
                {
                    b.HasOne("RoutePage.Model.Route", "Route")
                        .WithMany("Coordinates")
                        .HasForeignKey("RouteId");
                });
#pragma warning restore 612, 618
        }
    }
}
